apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-mongo-init-rs
data:
  init-replica-set.js: rs.initiate();
immutable: false

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-standalone
spec:
  serviceName: mongo
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
        selector: mongodb-standalone
    spec:
      volumes:
        - configMap:
            name: configmap-mongo-init-rs
          name: volume-mongo-init-rs
      containers:
        - name: mongodb-standalone
          image: mongo:7.0.1
          ports:
            - containerPort: 27017
          args: ["--replSet", "tilt", "--bind_ip_all"]
          readinessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 10
            periodSeconds: 30
            failureThreshold: 15
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: volume-mongo-init-rs

---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  clusterIP: None
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      name: mongo-port
